### PR TITLE
Add ssh

### PR DESCRIPTION
**Pull request by ritwik12**
Add ssh commands as requested by issue #8

### CODE REVIEW

**Comment by CodeMaxx** [comment]
Hey! Thanks for the PR.

Can you add more ssh flags which are commonly used, such as `ssh -X`, `ssh -t`?

**Comment by ritwik12** [comment]
@CodeMaxx Ya sure, let me add that.

**Comment by ritwik12** [comment]
@CodeMaxx Done :)

**Comment by CodeMaxx** [comment]
Awesome! Few more changes required. Since this is a repository to help beginners, the descriptions would have to be made a little more intuitive. For e.g. rather than saying `Enables X11 forwarding.`, say something like `Enables X11 forwarding which lets you run graphical applications remotely`; basically in a way you would've liked someone else to explain to you before you learnt about it 😃

**Comment by ritwik12** [comment]
@CodeMaxx Good to go I guess.

**Comment by CodeMaxx** [comment]
Merged! Thanks :)

**Comment by ritwik12** [comment]
@CodeMaxx Your welcome :)

**Pull request merged**
